[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# optimizer = true
# optimization_runs = 200
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./storage"}, { access = "read", path = "./swaps.json" }, { access = "read", path = "./swaps-v4.json" }, { access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
